name: Format code and lint

on: [push, pull_request]

jobs:
  format-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Format code
        run: yarn format

      - name: Lint code and fix
        run: yarn lint:fix
